package com.ayaz.technicalcalculator;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 LinearLayout root,body; SharedPreferences sp; double usd=201000; int blue=Color.rgb(18,59,93), gold=Color.rgb(231,169,43), bg=Color.rgb(245,247,250); Typeface bold=Typeface.DEFAULT_BOLD;
 String shop="فروشگاه تجهیزات حفاظتی و نظارتی آیاز", phone="۰۹۳۹۴۵۶۹۱۳۱", address="آذربایجان شرقی", instagram="@Ayazcctv";
 @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(blue);sp=getSharedPreferences("ayaz",0);usd=sp.getFloat("usd",201000); showHome();}
 TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.rgb(23,33,43));t.setGravity(Gravity.CENTER);t.setPadding(18,14,18,14);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackgroundColor(blue);b.setPadding(8,8,8,8);return b;}
 EditText edit(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(16);e.setInputType(2|8192);e.setGravity(Gravity.RIGHT);e.setPadding(20,8,20,8);return e;}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(24,18,24,28);sv.addView(body); TextView h=tv(title,22);h.setTypeface(bold);h.setTextColor(Color.WHITE);h.setBackgroundColor(blue);h.setPadding(20,20,20,20);root.addView(h);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void add(View v){body.addView(v,new LinearLayout.LayoutParams(-1,LinearLayout.LayoutParams.WRAP_CONTENT));}
 void spacer(){Space s=new Space(this);add(s);s.getLayoutParams().height=18;}
 void showHome(){base("محاسبه نیازهای فنی فروشگاه آیاز"); TextView info=tv("آیاز\nتجهیزات حفاظتی و نظارتی\n"+address+"\n"+phone+"   |   "+instagram,17);info.setTypeface(bold);add(info);spacer();Button c=btn("📷  دوربین مداربسته");Button a=btn("🔔  دزدگیر اماکن");Button so=btn("☀  برق خورشیدی");add(c);spacer();add(a);spacer();add(so);spacer();Button ad=btn("⚙  مدیریت");add(ad);c.setOnClickListener(v->cctvLevel());a.setOnClickListener(v->alarm());so.setOnClickListener(v->solar());ad.setOnClickListener(v->adminLogin());}
 void cctvLevel(){base("دوربین مداربسته");add(tv("سطح پروژه را انتخاب کنید",19));String[] names={"اقتصادی\nمناسب منزل","هوشمند\nمناسب منزل، فروشگاه و دفتر","حرفه‌ای\nمناسب کارخانه و پروژه‌های حساس"};for(int i=0;i<3;i++){Button b=btn(names[i]);final int x=i;add(b);spacer();b.setOnClickListener(v->cctvCount(x));}}
 void cctvCount(int level){base("تعداد دوربین");add(tv("سطح: "+new String[]{"اقتصادی","هوشمند","حرفه‌ای"}[level],18));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);Button minus=btn("−"),plus=btn("+");TextView n=tv("4",28);n.setTypeface(bold);row.addView(minus,new LinearLayout.LayoutParams(80,70));row.addView(n,new LinearLayout.LayoutParams(0,70,1));row.addView(plus,new LinearLayout.LayoutParams(80,70));add(row);minus.setOnClickListener(v->{int q=Math.max(1,Integer.parseInt(n.getText().toString())-1);n.setText(""+q);});plus.setOnClickListener(v->{int q=Math.min(64,Integer.parseInt(n.getText().toString())+1);n.setText(""+q);});spacer();Button go=btn("محاسبه پیش‌فاکتور");add(go);go.setOnClickListener(v->cctvQuote(level,Integer.parseInt(n.getText().toString())));}
 String money(double x){return String.format(Locale.US,"%,.0f تومان",x);}
 void cctvQuote(int level,int cams){base("پیش‌فاکتور اولیه دوربین");String[] lv={"اقتصادی","هوشمند","حرفه‌ای"};add(tv("سطح: "+lv[level]+"   |   تعداد دوربین: "+cams,17));double total=0;ArrayList<String> lines=new ArrayList<>();double cam=(level==0?25:level==1?45:70)*usd;lines.add("دوربین "+(level==0?"AHD 2MP":level==1?"AHD 5MP":"AHD 5MP / IP 5MP")+" × "+cams+" = "+money(cam*cams));total+=cam*cams;lines.add("آداپتور × "+cams+" = "+money(3*usd*cams));total+=3*usd*cams;lines.add("فیش BNC × "+(cams*2)+" = "+money(.5*usd*cams*2));total+=usd*cams;lines.add("کابل × "+(cams*30)+" متر = "+money(.08*usd*cams*30));total+=.08*usd*cams*30;lines.add("داکت × "+(cams*3)+" متر = "+money(.04*usd*cams*3));total+=.04*usd*cams*3;int ch=cams<=4?4:cams<=8?8:cams<=16?16:32;lines.add((level==2?"NVR/DVR":"DVR")+" "+ch+" کانال × 1 = "+money((ch==4?35:ch==8?55:ch==16?85:130)*usd));total+=(ch==4?35:ch==8?55:ch==16?85:130)*usd;lines.add("هارد × 1 = "+money((cams<=4?5:cams<=8?10:cams<=16?20:35)*usd));total+=(cams<=4?5:cams<=8?10:cams<=16?20:35)*usd;lines.add("محافظ برق × 1 = "+money(4*usd));total+=4*usd;lines.add("کمباکس × "+cams+" = "+money(2*usd*cams));total+=2*usd*cams;for(String s:lines)add(tv(s,15));spacer();TextView tt=tv("جمع کل تقریبی: "+money(total),20);tt.setTypeface(bold);add(tt);add(tv("نرخ دلار: "+money(usd)+"\nاین پیش‌فاکتور صرفاً برآورد اولیه است.",14));Button back=btn("بازگشت");add(back);back.setOnClickListener(v->showHome());}
 void alarm(){base("دزدگیر اماکن");add(tv("تعداد ورودی‌ها / نقاط ورود را وارد کنید",18));EditText e=edit("مثلاً 3","3");e.setInputType(2);add(e);spacer();Button go=btn("محاسبه پیش‌فاکتور");add(go);go.setOnClickListener(v->{int q=Math.max(1,Integer.parseInt(e.getText().toString()));alarmQuote(q);});}
 void alarmQuote(int q){base("پیش‌فاکتور اولیه دزدگیر");double total=0;String[] ls={"مرکز کنترل × 1","باتری × 1","چشمی × "+q,"ریموت × "+q,"سیرن × 1","کابل × "+(q*20)+" متر"};double[] p={35,8,4,3,7,.08};int[] qty={1,1,q,q,1,q*20};for(int i=0;i<ls.length;i++){double x=p[i]*usd*qty[i];total+=x;add(tv(ls[i]+" = "+money(x),15));}spacer();TextView t=tv("جمع کل تقریبی: "+money(total),20);t.setTypeface(bold);add(t);add(tv("برآورد اولیه؛ مقادیر و قیمت‌ها از بخش مدیریت قابل تغییرند.",14));Button b=btn("بازگشت");add(b);b.setOnClickListener(v->showHome());}
 void solar(){base("برق خورشیدی");add(tv("مصرف‌کننده‌ها را اضافه کنید",18));LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);add(list);Button add=btn("＋ افزودن وسیله");add(add);add(new View(this),new LinearLayout.LayoutParams(1,12));Button calc=btn("محاسبه سیستم خورشیدی");add(calc);add.setOnClickListener(v->applianceDialog(list));calc.setOnClickListener(v->solarResult(list));}
 void applianceDialog(LinearLayout list){String[] a={"لامپ 25W","یخچال 18 فوت","تلویزیون 55 اینچ","کولر گازی 18000","پمپ 1 اسب"};new AlertDialog.Builder(this).setTitle("انتخاب وسیله").setItems(a,(d,w)->{LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView name=tv(a[w],15);name.setGravity(Gravity.RIGHT);EditText qty=edit("تعداد","1");EditText hrs=edit("ساعت/روز","4");r.addView(name,new LinearLayout.LayoutParams(0,70,1));r.addView(qty,new LinearLayout.LayoutParams(75,70));r.addView(hrs,new LinearLayout.LayoutParams(90,70));list.addView(r);}).show();}
 void solarResult(LinearLayout list){double[] powers={25,180,120,1800,750};double energy=0,peak=0;for(int i=0;i<list.getChildCount();i++){View v=list.getChildAt(i);if(!(v instanceof LinearLayout))continue;LinearLayout r=(LinearLayout)v;String s=((TextView)r.getChildAt(0)).getText().toString();int idx=0;for(int j=0;j<5;j++)if(s.startsWith(new String[]{"لامپ","یخچال","تلویزیون","کولر","پمپ"}[j]))idx=j;int q=Integer.parseInt(((EditText)r.getChildAt(1)).getText().toString());double h=Double.parseDouble(((EditText)r.getChildAt(2)).getText().toString());energy+=powers[idx]*q*h;peak+=powers[idx]*q;}double pv=Math.ceil(energy/(5*0.78)/550);double batteryAh=Math.ceil(energy*1.5/24);double inverter=Math.ceil((peak*1.25)/500)*500;new AlertDialog.Builder(this).setTitle("نتیجه برآورد خورشیدی").setMessage("انرژی روزانه: "+String.format(Locale.US,"%.0f Wh",energy)+"\nبار همزمان: "+String.format(Locale.US,"%.0f W",peak)+"\nپنل 550W: "+(int)pv+" عدد\nظرفیت تقریبی باتری: "+(int)batteryAh+" Ah\nاینورتر پیشنهادی: "+(int)inverter+" W\n\nنتیجه مقدماتی است و برای طراحی نهایی باید شرایط محل بررسی شود.").setPositiveButton("باشه",null).show();}
 void adminLogin(){final EditText e=edit("رمز مدیریت","2580");e.setInputType(2|8192);new AlertDialog.Builder(this).setTitle("ورود مدیریت").setView(e).setPositiveButton("ورود",(d,w)->{if(e.getText().toString().equals("2580"))admin();else Toast.makeText(this,"رمز اشتباه است",Toast.LENGTH_SHORT).show();}).setNegativeButton("لغو",null).show();}
 void admin(){base("مدیریت برنامه");add(tv("تنظیمات محلی برنامه",19));add(tv("نرخ دلار به تومان",15));EditText rate=edit("نرخ دلار",String.valueOf((long)usd));add(rate);Button save=btn("ذخیره نرخ دلار");add(save);save.setOnClickListener(v->{try{usd=Double.parseDouble(rate.getText().toString());sp.edit().putFloat("usd",(float)usd).apply();Toast.makeText(this,"ذخیره شد",Toast.LENGTH_SHORT).show();}catch(Exception x){}});spacer();add(tv("اطلاعات فروشگاه",17));EditText ph=edit("موبایل",phone);add(ph);EditText ad=edit("آدرس",address);add(ad);EditText ins=edit("اینستاگرام",instagram);add(ins);Button saveInfo=btn("ذخیره اطلاعات فروشگاه");add(saveInfo);saveInfo.setOnClickListener(v->{phone=ph.getText().toString();address=ad.getText().toString();instagram=ins.getText().toString();sp.edit().putString("phone",phone).putString("address",address).putString("instagram",instagram).apply();Toast.makeText(this,"ذخیره شد",Toast.LENGTH_SHORT).show();});spacer();add(tv("نسخه 1.0.0 — آفلاین",14));Button b=btn("بازگشت");add(b);b.setOnClickListener(v->showHome());}
}
